### ISSUE TITLE
Broken recoil

### ISSUE THREAD

**Issue by itzH97** [NoobySloth/Custom-Weapons#12]
after i installed this script i have no problems everything is working no errors or issue apart from now for the custom and default weapons my recoil is not working how do i fix this?

i tried to up the recoil on these weapons and nothing happened i tested my default which i new worked before adding this script and they are the same

![image](https://user-images.githubusercontent.com/128502120/226654069-6726a7fb-57bd-4ccd-9882-97254725c6a9.png)

**Comment by LeSiiN** [comment]
workign for me, so its a u problem
