### ISSUE TITLE
New Images!

### ISSUE THREAD

**Issue by Glunkussss** [NoobySloth/Custom-Weapons#13]
I make some new images for inventory
![weapon_colbaton](https://github.com/NoobySloth/Custom-Weapons/assets/102635797/a15744e7-12a0-47f0-aaf8-4f4975936cb4)
![weapon_m9](https://github.com/NoobySloth/Custom-Weapons/assets/102635797/811768f0-c475-4594-aba7-9961de5ab2d1)
![weapon_mp9](https://github.com/NoobySloth/Custom-Weapons/assets/102635797/27c8c5a7-3f2a-435b-ac07-0251e127a5dd)
![glock-18c](https://github.com/NoobySloth/Custom-Weapons/assets/102635797/65fdd171-da23-4cc4-b661-af46fb2c3d6b)

**Comment by Glunkussss** [comment]
It will be good that u add it on the images ( i made just de colbaton-m9-mp9 / the glock18c i found it not mine)

**Comment by NoobySloth** [comment]
> It will be good that u add it on the images ( i made just de colbaton-m9-mp9 / the glock18c i found it not mine)

They look great! I will add this, thank you!
