### ISSUE TITLE
Missing meta Folder

### ISSUE THREAD

**Issue by TankinTom** [NoobySloth/Custom-Weapons#16]
The Glock17 and M1911 Are missing the meta folders. For some reason, only those two weapons are the only ones I'm unable to take out in my hands. Literally every other weapons works.

**Comment by NoobySloth** [comment]
As per latest [574b370](https://github.com/NoobySloth/Custom-Weapons/commit/574b370a995de0469e89b72d50792d40c7b2dc5c) these two weapons have been removed due to the owner wanting them removed.

**Comment by TankinTom** [comment]
Gotcha, gotcha. Might I recommend taking the items out of the readme then, Just to avoid confusion?
