### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by NatasWillDoIt** [NoobySloth/Custom-Weapons#3]
when i call any of the weapons t dont spawn the weapon i hae tried tons of things with not one weapon working

**Comment by NatasWillDoIt** [comment]
when u seacrh the consol it say only the katana loads but once u try to use it it dont load it

**Comment by NoobySloth** [comment]
You've done it wrong then. Delete it and reinstall and follow every step

**Comment by jaylac2000** [comment]
^^ à elegant for me

**Comment by LeSiiN** [comment]
CLOSED
